name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: [ '26' ]       # Define the OTP version [required]
        elixir: [ '1.17.2' ]    # Define the elixir version [required]
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fix ssl verify error
        run: mix deps.unlock ssl_verify_fun

      - name: Install Dependencies
        run: mix deps.get

      - name: Compiles without warnings
        run: mix compile

      - name: Run Tests
        run: mix test

  Linting:
    runs-on: ubuntu-latest
    strategy:
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: [ '26' ]       # Define the OTP version [required]
        elixir: [ '1.17.2' ]    # Define the elixir version [required]
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fix ssl verify error
        run: mix deps.unlock ssl_verify_fun

      - name: Install Dependencies
        run: mix deps.get

      - name: Compiles without warnings
        run: mix compile

      - name: Run Formatter
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo
